### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by depthso** [NotDevX/Crinox#1]
![image](https://github.com/NotDevX/Crinox/assets/86912923/a1c07325-ed55-4b8c-8147-d7357c0c34ec)

**Comment by depthso** [comment]
![image](https://github.com/NotDevX/Crinox/assets/86912923/78debfe8-5a7e-485a-8438-054da9ca73bc)

**Comment by depthso** [comment]
![image](https://github.com/NotDevX/Crinox/assets/86912923/6c92197a-0a07-4605-91c5-275409863a0d)

**Comment by NotDevX** [comment]
depso why did you do this. all i sent was the realistic tiger sticker.

**Comment by depthso** [comment]
😱
